
circle(container1_1,nil).
circle(container1_2,nil).
color(container1_4,"green").
color(container1_5,"yellow").
contains(container1_0,container1_1).
contains(container1_0,container1_2).
contains(container1_0,container1_3).
contains(container1_3,container1_4).
contains(container1_3,container1_5).
rect(container1_0,nil).
rect(container1_3,nil).
rect(container1_4,nil).
rect(container1_5,nil).
rounded(container1_0,nil).
synonym(container1_0,container1).
synonym(container1_1,x).
synonym(container1_2,y).
synonym(container1_3,hello).
synonym(container1_4,hello_r).
synonym(container1_5,hello_s).
