arrow(container1_6_a,nil).
arrow(container1_7_a,nil).
circle(container1_1,nil).
circle(container1_2,nil).
color(container1_1,"green").
color(container1_2,"yellow").
color(container1_4,"green").
color(container1_5,"yellow").
contains(container1_0,container1_1).
contains(container1_0,container1_2).
contains(container1_0,container1_3).
contains(container1_0,container1_6).
contains(container1_0,container1_7).
contains(container1_3,container1_4).
contains(container1_3,container1_5).
receiversynonym(container1_6_a,hello_r).
receiversynonym(container1_7_a,y).
rect(container1_0,nil).
rect(container1_3,nil).
rect(container1_4,nil).
rect(container1_5,nil).
rounded(container1_0,nil).
rounded(container1_3,nil).
sendersynonym(container1_6_a,x).
sendersynonym(container1_7_a,hello_s).
synonym(container1_0,container1).
synonym(container1_1,x).
synonym(container1_2,y).
synonym(container1_3,hello).
synonym(container1_4,hello_r).
synonym(container1_5,hello_s).
