

arrow(v_23,nil).
arrow(v_24,nil).
arrow(v_25,nil).
arrow(v_26,nil).
arrow(v_27,nil).
arrow(v_28,nil).
arrow(v_29,nil).
arrow(v_30,nil).
arrow(v_31,nil).
arrow(v_32,nil).
arrow(v_x_14,nil).
arrow(v_x_15,nil).
arrow(v_x_16,nil).
arrow(v_x_17,nil).
arrow(v_x_18,nil).
circle(v_1,nil).
circle(v_2,nil).
color(v_0,"F5F5F5FF").
color(v_10,"green").
color(v_11,"green").
color(v_12,"yellow").
color(v_13,"DBDBDBFF").
color(v_14,"green").
color(v_15,"green").
color(v_16,"yellow").
color(v_21,"green").
color(v_22,"yellow").
color(v_5,"green").
color(v_6,"green").
color(v_9,"E3E3E3FF").
color(v_x_0,"E3E3E3FF").
color(v_x_1,"green").
color(v_x_12,"green").
color(v_x_13,"yellow").
color(v_x_2,"green").
color(v_x_3,"yellow").
color(v_x_4,"DBDBDBFF").
color(v_x_5,"green").
color(v_x_6,"green").
color(v_x_7,"yellow").
contains(v_0,v_1).
contains(v_0,v_2).
contains(v_0,v_23).
contains(v_0,v_24).
contains(v_0,v_25).
contains(v_0,v_26).
contains(v_0,v_27).
contains(v_0,v_28).
contains(v_0,v_29).
contains(v_0,v_3).
contains(v_0,v_30).
contains(v_0,v_31).
contains(v_0,v_32).
contains(v_0,v_7).
contains(v_0,v_9).
contains(v_13,v_14).
contains(v_13,v_15).
contains(v_13,v_16).
contains(v_17,v_18).
contains(v_19,v_20).
contains(v_19,v_21).
contains(v_19,v_22).
contains(v_3,v_4).
contains(v_3,v_5).
contains(v_3,v_6).
contains(v_7,v_8).
contains(v_9,v_10).
contains(v_9,v_11).
contains(v_9,v_12).
contains(v_9,v_13).
contains(v_9,v_17).
contains(v_9,v_19).
contains(v_x_0,v_x_1).
contains(v_x_0,v_x_10).
contains(v_x_0,v_x_14).
contains(v_x_0,v_x_15).
contains(v_x_0,v_x_16).
contains(v_x_0,v_x_17).
contains(v_x_0,v_x_18).
contains(v_x_0,v_x_2).
contains(v_x_0,v_x_3).
contains(v_x_0,v_x_4).
contains(v_x_0,v_x_8).
contains(v_x_10,v_x_11).
contains(v_x_10,v_x_12).
contains(v_x_10,v_x_13).
contains(v_x_4,v_x_5).
contains(v_x_4,v_x_6).
contains(v_x_4,v_x_7).
contains(v_x_8,v_x_9).
ellipse(v_17,nil).
ellipse(v_7,nil).
ellipse(v_x_8,nil).
receiversynonym(v_23,v_x_y_a).
receiversynonym(v_24,v_x_y_b).
receiversynonym(v_25,v_x_c).
receiversynonym(v_26,v_x_d_a).
receiversynonym(v_27,v_x_e).
receiversynonym(v_28,v_x_a).
receiversynonym(v_29,v_b_a).
receiversynonym(v_30,v_c).
receiversynonym(v_31,v_x_b).
receiversynonym(v_32,v_d).
receiversynonym(v_x_14,v_x_y_a).
receiversynonym(v_x_15,v_x_y_b).
receiversynonym(v_x_16,v_x_c).
receiversynonym(v_x_17,v_x_d_a).
receiversynonym(v_x_18,v_x_e).
rect(v_0,nil).
rect(v_10,nil).
rect(v_11,nil).
rect(v_12,nil).
rect(v_13,nil).
rect(v_14,nil).
rect(v_15,nil).
rect(v_16,nil).
rect(v_19,nil).
rect(v_21,nil).
rect(v_22,nil).
rect(v_3,nil).
rect(v_5,nil).
rect(v_6,nil).
rect(v_9,nil).
rect(v_x_0,nil).
rect(v_x_1,nil).
rect(v_x_10,nil).
rect(v_x_12,nil).
rect(v_x_13,nil).
rect(v_x_2,nil).
rect(v_x_3,nil).
rect(v_x_4,nil).
rect(v_x_5,nil).
rect(v_x_6,nil).
rect(v_x_7,nil).
rounded(v_0,nil).
rounded(v_13,nil).
rounded(v_19,nil).
rounded(v_3,nil).
rounded(v_9,nil).
rounded(v_x_0,nil).
rounded(v_x_10,nil).
rounded(v_x_4,nil).
sendersynonym(v_23,v_x_a).
sendersynonym(v_24,v_x_b).
sendersynonym(v_25,v_x_y_c).
sendersynonym(v_26,v_x_c).
sendersynonym(v_27,v_x_d_b).
sendersynonym(v_28,v_a).
sendersynonym(v_29,v_a).
sendersynonym(v_30,v_b_b).
sendersynonym(v_31,v_c).
sendersynonym(v_32,v_x_c).
sendersynonym(v_x_14,v_x_a).
sendersynonym(v_x_15,v_x_b).
sendersynonym(v_x_16,v_x_y_c).
sendersynonym(v_x_17,v_x_c).
sendersynonym(v_x_18,v_x_d_b).
str(v_18,"completed runnable").
str(v_20,"make it runnable").
str(v_4,"make empty runnable").
str(v_8,"empty runnable").
str(v_x_11,"make it runnable").
str(v_x_9,"completed runnable").
synonym(v_0,v).
synonym(v_1,v_a).
synonym(v_10,v_x_a).
synonym(v_11,v_x_b).
synonym(v_12,v_x_c).
synonym(v_13,v_x_y).
synonym(v_14,v_x_y_a).
synonym(v_15,v_x_y_b).
synonym(v_16,v_x_y_c).
synonym(v_17,v_x_c).
synonym(v_19,v_x_d).
synonym(v_2,v_d).
synonym(v_21,v_x_d_a).
synonym(v_22,v_x_d_b).
synonym(v_3,v_b).
synonym(v_5,v_b_a).
synonym(v_6,v_b_b).
synonym(v_7,v_c).
synonym(v_9,v_x).
synonym(v_x_0,v_x).
synonym(v_x_1,v_x_a).
synonym(v_x_10,v_x_d).
synonym(v_x_12,v_x_d_a).
synonym(v_x_13,v_x_d_b).
synonym(v_x_2,v_x_b).
synonym(v_x_3,v_x_c).
synonym(v_x_4,v_x_y).
synonym(v_x_5,v_x_y_a).
synonym(v_x_6,v_x_y_b).
synonym(v_x_7,v_x_y_c).
synonym(v_x_8,v_x_c).
text(v_18,nil).
text(v_20,nil).
text(v_4,nil).
text(v_8,nil).
text(v_x_11,nil).
text(v_x_9,nil).
