

arrow(v_10,nil).
arrow(v_11,nil).
arrow(v_12,nil).
arrow(v_13,nil).
arrow(v_9,nil).
arrow(v_x_14,nil).
arrow(v_x_15,nil).
arrow(v_x_16,nil).
arrow(v_x_17,nil).
arrow(v_x_18,nil).
circle(v_1,nil).
circle(v_2,nil).
color(v_0,"F5F5F5FF").
color(v_5,"green").
color(v_6,"green").
color(v_x_0,"E3E3E3FF").
color(v_x_1,"green").
color(v_x_12,"green").
color(v_x_13,"yellow").
color(v_x_2,"green").
color(v_x_3,"yellow").
color(v_x_4,"DBDBDBFF").
color(v_x_5,"green").
color(v_x_6,"green").
color(v_x_7,"yellow").
contains(v_0,v_1).
contains(v_0,v_10).
contains(v_0,v_11).
contains(v_0,v_12).
contains(v_0,v_13).
contains(v_0,v_2).
contains(v_0,v_3).
contains(v_0,v_7).
contains(v_0,v_9).
contains(v_3,v_4).
contains(v_3,v_5).
contains(v_3,v_6).
contains(v_7,v_8).
contains(v_x_0,v_x_1).
contains(v_x_0,v_x_10).
contains(v_x_0,v_x_14).
contains(v_x_0,v_x_15).
contains(v_x_0,v_x_16).
contains(v_x_0,v_x_17).
contains(v_x_0,v_x_18).
contains(v_x_0,v_x_2).
contains(v_x_0,v_x_3).
contains(v_x_0,v_x_4).
contains(v_x_0,v_x_8).
contains(v_x_10,v_x_11).
contains(v_x_10,v_x_12).
contains(v_x_10,v_x_13).
contains(v_x_4,v_x_5).
contains(v_x_4,v_x_6).
contains(v_x_4,v_x_7).
contains(v_x_8,v_x_9).
ellipse(v_7,nil).
ellipse(v_x_8,nil).
receiversynonym(v_10,v_b_a).
receiversynonym(v_11,v_c).
receiversynonym(v_12,v_x_b).
receiversynonym(v_13,v_d).
receiversynonym(v_9,v_x_a).
receiversynonym(v_x_14,v_x_y_a).
receiversynonym(v_x_15,v_x_y_b).
receiversynonym(v_x_16,v_x_c).
receiversynonym(v_x_17,v_x_d_a).
receiversynonym(v_x_18,v_x_e).
rect(v_0,nil).
rect(v_3,nil).
rect(v_5,nil).
rect(v_6,nil).
rect(v_x_0,nil).
rect(v_x_1,nil).
rect(v_x_10,nil).
rect(v_x_12,nil).
rect(v_x_13,nil).
rect(v_x_2,nil).
rect(v_x_3,nil).
rect(v_x_4,nil).
rect(v_x_5,nil).
rect(v_x_6,nil).
rect(v_x_7,nil).
rounded(v_0,nil).
rounded(v_3,nil).
rounded(v_x_0,nil).
rounded(v_x_10,nil).
rounded(v_x_4,nil).
sendersynonym(v_10,v_a).
sendersynonym(v_11,v_b_b).
sendersynonym(v_12,v_c).
sendersynonym(v_13,v_x_c).
sendersynonym(v_9,v_a).
sendersynonym(v_x_14,v_x_a).
sendersynonym(v_x_15,v_x_b).
sendersynonym(v_x_16,v_x_y_c).
sendersynonym(v_x_17,v_x_c).
sendersynonym(v_x_18,v_x_d_b).
str(v_4,"make empty runnable").
str(v_8,"empty runnable").
str(v_x_11,"make it runnable").
str(v_x_9,"completed runnable").
synonym(v_0,v).
synonym(v_1,v_a).
synonym(v_2,v_d).
synonym(v_3,v_b).
synonym(v_5,v_b_a).
synonym(v_6,v_b_b).
synonym(v_7,v_c).
synonym(v_x_0,v_x).
synonym(v_x_1,v_x_a).
synonym(v_x_10,v_x_d).
synonym(v_x_12,v_x_d_a).
synonym(v_x_13,v_x_d_b).
synonym(v_x_2,v_x_b).
synonym(v_x_3,v_x_c).
synonym(v_x_4,v_x_y).
synonym(v_x_5,v_x_y_a).
synonym(v_x_6,v_x_y_b).
synonym(v_x_7,v_x_y_c).
synonym(v_x_8,v_x_c).
text(v_4,nil).
text(v_8,nil).
text(v_x_11,nil).
text(v_x_9,nil).
