arrow(container1_6,nil).
arrow(container1_7,nil).
arrow(layer0_6,nil).
arrow(layer0_7,nil).
circle(container1_1,nil).
circle(container1_2,nil).
circle(layer0_1,nil).
circle(layer0_2,nil).
color(container1_4,"green").
color(container1_5,"yellow").
color(layer0_1,"green").
color(layer0_2,"yellow").
color(layer0_4,"green").
color(layer0_5,"yellow").
contains(container1_0,container1_1).
contains(container1_0,container1_2).
contains(container1_0,container1_3).
contains(container1_0,container1_6).
contains(container1_0,container1_7).
contains(container1_3,container1_4).
contains(container1_3,container1_5).
contains(layer0_0,container1_0).
contains(layer0_0,layer0_1).
contains(layer0_0,layer0_2).
contains(layer0_0,layer0_3).
contains(layer0_0,layer0_6).
contains(layer0_0,layer0_7).
contains(layer0_3,layer0_4).
contains(layer0_3,layer0_5).
orphan(layer0_3,nil).
receiversynonym(container1_6,hello_r).
receiversynonym(container1_7,y).
receiversynonym(layer0_6,layer1_a).
receiversynonym(layer0_7,out).
rect(container1_0,nil).
rect(container1_3,nil).
rect(container1_4,nil).
rect(container1_5,nil).
rect(layer0_0,nil).
rect(layer0_3,nil).
rect(layer0_4,nil).
rect(layer0_5,nil).
rounded(container1_0,nil).
rounded(container1_3,nil).
rounded(layer0_0,nil).
rounded(layer0_3,nil).
sendersynonym(container1_6,x).
sendersynonym(container1_7,hello_s).
sendersynonym(layer0_6,in).
sendersynonym(layer0_7,layer1_b).
synonym(container1_0,container1).
synonym(container1_1,x).
synonym(container1_2,y).
synonym(container1_3,hello).
synonym(container1_4,hello_r).
synonym(container1_5,hello_s).
synonym(layer0_0,layer0).
synonym(layer0_1,in).
synonym(layer0_2,out).
synonym(layer0_3,layer1).
synonym(layer0_4,layer1_a).
synonym(layer0_5,layer1_b).
