
arrow(v_13, nil).
arrow(v_14, nil).
arrow(v_15, nil).
arrow(v_16, nil).
arrow(v_17, nil).
circle(v_1, nil).
circle(v_2, nil).
color(v_0, "F5F5F5FF").
color(v_10, "green").
color(v_11, "green").
color(v_12, "yellow").
color(v_5, "green").
color(v_6, "green").
color(v_9, "E3E3E3FF").
contains(v_0, v_1).
contains(v_0, v_13).
contains(v_0, v_14).
contains(v_0, v_15).
contains(v_0, v_16).
contains(v_0, v_17).
contains(v_0, v_2).
contains(v_0, v_3).
contains(v_0, v_7).
contains(v_0, v_9).
contains(v_3, v_4).
contains(v_3, v_5).
contains(v_3, v_6).
contains(v_7, v_8).
contains(v_9, v_10).
contains(v_9, v_11).
contains(v_9, v_12).
ellipse(v_7, nil).
receiversynonym(v_13, "v_x_a").
receiversynonym(v_14, "v_b_a").
receiversynonym(v_15, "v_c").
receiversynonym(v_16, "v_x_b").
receiversynonym(v_17, "v_d").
rect(v_0, nil).
rect(v_10, nil).
rect(v_11, nil).
rect(v_12, nil).
rect(v_3, nil).
rect(v_5, nil).
rect(v_6, nil).
rect(v_9, nil).
rounded(v_0,nil).
rounded(v_3,nil).
rounded(v_9,nil).
sendersynonym(v_13, "v_a").
sendersynonym(v_14, "v_a").
sendersynonym(v_15, "v_b_b").
sendersynonym(v_16, "v_c").
sendersynonym(v_17, "v_x_c").
str(v_4, "make empty runnable").
str(v_8, "empty runnable").
synonym(v_0, "v").
synonym(v_1, "v_a").
synonym(v_10, "v_x_a").
synonym(v_11, "v_x_b").
synonym(v_12, "v_x_c").
synonym(v_2, "v_d").
synonym(v_3, "v_b").
synonym(v_5, "v_b_a").
synonym(v_6, "v_b_b").
synonym(v_7, "v_c").
synonym(v_9, "v_x").
text(v_4, nil).
text(v_8, nil).
