
arrow(v_10,nil).
arrow(v_11,nil).
arrow(v_12,nil).
arrow(v_13,nil).
arrow(v_9,nil).
circle(v_1,nil).
circle(v_2,nil).
color(v_0,"F5F5F5FF").
color(v_5,"green").
color(v_6,"green").
contains(v_0,v_1).
contains(v_0,v_10).
contains(v_0,v_11).
contains(v_0,v_12).
contains(v_0,v_13).
contains(v_0,v_2).
contains(v_0,v_3).
contains(v_0,v_7).
contains(v_0,v_9).
contains(v_3,v_4).
contains(v_3,v_5).
contains(v_3,v_6).
contains(v_7,v_8).
ellipse(v_7,nil).
receiversynonym(v_10,v_b_a).
receiversynonym(v_11,v_c).
receiversynonym(v_12,v_x_b).
receiversynonym(v_13,v_d).
receiversynonym(v_9,v_x_a).
rect(v_0,nil).
rect(v_3,nil).
rect(v_5,nil).
rect(v_6,nil).
rounded(v_0,nil).
rounded(v_3,nil).
sendersynonym(v_10,v_a).
sendersynonym(v_11,v_b_b).
sendersynonym(v_12,v_c).
sendersynonym(v_13,v_x_c).
sendersynonym(v_9,v_a).
str(v_4,"make empty runnable").
str(v_8,"empty runnable").
synonym(v_0,v).
synonym(v_1,v_a).
synonym(v_2,v_d).
synonym(v_3,v_b).
synonym(v_5,v_b_a).
synonym(v_6,v_b_b).
synonym(v_7,v_c).
text(v_4,nil).
text(v_8,nil).
