
arrow(v_x_14,nil).
arrow(v_x_15,nil).
arrow(v_x_16,nil).
arrow(v_x_17,nil).
arrow(v_x_18,nil).
color(v_x_0,"E3E3E3FF").
color(v_x_1,"green").
color(v_x_12,"green").
color(v_x_13,"yellow").
color(v_x_2,"green").
color(v_x_3,"yellow").
color(v_x_4,"DBDBDBFF").
color(v_x_5,"green").
color(v_x_6,"green").
color(v_x_7,"yellow").
contains(v_x_0,v_x_1).
contains(v_x_0,v_x_10).
contains(v_x_0,v_x_14).
contains(v_x_0,v_x_15).
contains(v_x_0,v_x_16).
contains(v_x_0,v_x_17).
contains(v_x_0,v_x_18).
contains(v_x_0,v_x_2).
contains(v_x_0,v_x_3).
contains(v_x_0,v_x_4).
contains(v_x_0,v_x_8).
contains(v_x_10,v_x_11).
contains(v_x_10,v_x_12).
contains(v_x_10,v_x_13).
contains(v_x_4,v_x_5).
contains(v_x_4,v_x_6).
contains(v_x_4,v_x_7).
contains(v_x_8,v_x_9).
ellipse(v_x_8,nil).
receiversynonym(v_x_14,v_x_y_a).
receiversynonym(v_x_15,v_x_y_b).
receiversynonym(v_x_16,v_x_c).
receiversynonym(v_x_17,v_x_d_a).
receiversynonym(v_x_18,v_x_e).
rect(v_x_0,nil).
rect(v_x_1,nil).
rect(v_x_10,nil).
rect(v_x_12,nil).
rect(v_x_13,nil).
rect(v_x_2,nil).
rect(v_x_3,nil).
rect(v_x_4,nil).
rect(v_x_5,nil).
rect(v_x_6,nil).
rect(v_x_7,nil).
rounded(v_x_0,nil).
rounded(v_x_10,nil).
rounded(v_x_4,nil).
sendersynonym(v_x_14,v_x_a).
sendersynonym(v_x_15,v_x_b).
sendersynonym(v_x_16,v_x_y_c).
sendersynonym(v_x_17,v_x_c).
sendersynonym(v_x_18,v_x_d_b).
str(v_x_11,"make it runnable").
str(v_x_9,"completed runnable").
synonym(v_x_0,v_x).
synonym(v_x_1,v_x_a).
synonym(v_x_10,v_x_d).
synonym(v_x_12,v_x_d_a).
synonym(v_x_13,v_x_d_b).
synonym(v_x_2,v_x_b).
synonym(v_x_3,v_x_c).
synonym(v_x_4,v_x_y).
synonym(v_x_5,v_x_y_a).
synonym(v_x_6,v_x_y_b).
synonym(v_x_7,v_x_y_c).
synonym(v_x_8,v_x_c).
text(v_x_11,nil).
text(v_x_9,nil).
