
arrow(v_x_y_10,nil).
arrow(v_x_y_11,nil).
arrow(v_x_y_9,nil).
color(v_x_y_0,"DBDBDBFF").
color(v_x_y_2,"green").
color(v_x_y_3,"green").
color(v_x_y_5,"green").
color(v_x_y_6,"green").
color(v_x_y_7,"yellow").
color(v_x_y_8,"yellow").
contains(v_x_y_0,v_x_y_1).
contains(v_x_y_0,v_x_y_10).
contains(v_x_y_0,v_x_y_11).
contains(v_x_y_0,v_x_y_2).
contains(v_x_y_0,v_x_y_3).
contains(v_x_y_0,v_x_y_4).
contains(v_x_y_0,v_x_y_8).
contains(v_x_y_0,v_x_y_9).
contains(v_x_y_4,v_x_y_5).
contains(v_x_y_4,v_x_y_6).
contains(v_x_y_4,v_x_y_7).
receiversynonym(v_x_y_10,v_x_y_z_b).
receiversynonym(v_x_y_11,v_x_y_c).
receiversynonym(v_x_y_9,v_x_y_z_a).
rect(v_x_y_0,nil).
rect(v_x_y_2,nil).
rect(v_x_y_3,nil).
rect(v_x_y_4,nil).
rect(v_x_y_5,nil).
rect(v_x_y_6,nil).
rect(v_x_y_7,nil).
rect(v_x_y_8,nil).
rounded(v_x_y_0,nil).
rounded(v_x_y_4,nil).
sendersynonym(v_x_y_10,v_x_y_b).
sendersynonym(v_x_y_11,v_x_y_z_c).
sendersynonym(v_x_y_9,v_x_y_a).
str(v_x_y_1,"complete runnable").
synonym(v_x_y_0,v_x_y).
synonym(v_x_y_2,v_x_y_a).
synonym(v_x_y_3,v_x_y_b).
synonym(v_x_y_4,v_x_y_z).
synonym(v_x_y_5,v_x_y_z_a).
synonym(v_x_y_6,v_x_y_z_b).
synonym(v_x_y_7,v_x_y_z_c).
synonym(v_x_y_8,v_x_y_c).
text(v_x_y_1,nil).
